export const words = {
  headerTitle: "Shopping Cart",
  footerTitle: "© CopyRight Mostafa Sayed @2023",
  content: "Content",
  cartHeader: "There ",
  cartHeaderEnd: "in cart",
  cartTitle: "Title",
  cartQty: "qty",
  cartPrice: "price",
  removeBtn: "Remove",
  selectProducts: "select products",
  total: "Total",
  checkout: "Checkout",
  name: "Name",
  email: "Email",
  filterNoOfProducts: "number of products",
  filterTitle: "Filter",
  filterOrder: "Order",
};
export const arabicWords = {
  headerTitle: "عربه المشتريات",
  footerTitle: "© CopyRight Mostafa Sayed @2023",
  content: "المحتوي",
  cartHeader: "يوجد ",
  cartHeaderEnd: "في العربه",
  cartTitle: "العنوان",
  cartQty: "الكميه",
  cartPrice: "السعر",
  removeBtn: "حذف",
  selectProducts: "اختيار المنتجات",
  total: "السعر الكلي",
  checkout: "Checkout",
  name: "الاسم",
  email: "البريد الالكتروني",
  filterNoOfProducts: "عدد المنتجات",
  filterTitle: "تصنيف",
  filterOrder: "طلب",
};
