export const words = {
  headerTitle: "Shopping Cart",
  footerTitle: "© CopyRight Mostafa Sayed @2023",
  content: "Content",
  cartHeader: "There ",
  cartHeaderEnd: "in cart",
  cartTitle: "Title",
  cartQty: "qty",
  cartPrice: "price",
  removeBtn: "Remove",
  selectProducts: "select products",
  total: "Total",
  checkout: "Checkout",
  name: "Name",
  email: "Email",
  filterNoOfProducts: "number of products",
  filterTitle: "Filter",
  filterOrder: "Order",
};
